### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by suijunqiang** [prscX/react-native-photo-editor#25]
this is my reproduce steps & npm error log as bottom:
0, git clone https://github.com/prscX/react-native-photo-editor.git
1, cd react-native-photo-editor
2, npm install
(by the way, my npm --version 5.3.0)

> husky@0.14.3 install /Users/SJQ/Desktop/dev/rn/react-native-photo-editor/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
done

> prettier-pack@0.0.7 postinstall /Users/SJQ/Desktop/dev/rn/react-native-photo-editor/node_modules/prettier-pack
> node script.js && code --install-extension dbaeumer.vscode-eslint && code --install-extension esbenp.prettier-vscode

sh: code: command not found
npm WARN react-native-photo-editor@0.0.6 license should be a valid SPDX license expression

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! prettier-pack@0.0.7 postinstall: `node script.js && code --install-extension dbaeumer.vscode-eslint && code --install-extension esbenp.prettier-vscode`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the prettier-pack@0.0.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/SJQ/.npm/_logs/2018-11-21T10_38_59_001Z-debug.log

**Comment by suijunqiang** [comment]
The issue has been fixed by installing VSCode & linking code into $PATH;

But after that, still throw other npm install errors as below:

 husky@0.14.3 install /Users/SJQ/Desktop/dev/rn/react-native-photo-editor/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
done


> prettier-pack@0.0.7 postinstall /Users/SJQ/Desktop/dev/rn/react-native-photo-editor/node_modules/prettier-pack
> node script.js && code --install-extension dbaeumer.vscode-eslint && code --install-extension esbenp.prettier-vscode

Extension 'dbaeumer.vscode-eslint' is already installed.
Found 'esbenp.prettier-vscode' in the marketplace.
Installing...
Extension 'esbenp.prettier-vscode' v1.7.2 was successfully installed!

> react-native-photo-editor@0.0.6 postinstall /Users/SJQ/Desktop/dev/rn/react-native-photo-editor
> node ../pod-installer/index.js

module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/SJQ/Desktop/dev/rn/pod-installer/index.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-photo-editor@0.0.6 postinstall: `node ../pod-installer/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-photo-editor@0.0.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/SJQ/.npm/_logs/2018-11-23T01_09_04_933Z-debug.log

**Comment by suijunqiang** [comment]
Finially, the Example able to build successful on XCode 9.4.1, but it is crash after lunching with the error as below:
dyld: Library not loaded: @rpath/iOSPhotoEditor.framework/iOSPhotoEditor

**Comment by suijunqiang** [comment]
full crash log:
dyld: Library not loaded: @rpath/iOSPhotoEditor.framework/iOSPhotoEditor
  Referenced from: /Users/SJQ/Library/Developer/CoreSimulator/Devices/E6118C81-B41E-4C91-8004-617D61681883/data/Containers/Bundle/Application/1B41BEEE-D9C7-4C7B-B6AC-EAE27FF9EA0D/Example.app/Example
  Reason: image not found

**Comment by suijunqiang** [comment]
Hello, @prscX 

Thanks for your support, you project works fine now.

After settings & buildings as above, re checkout your ios code by git then use xcode 9.4.1/10.1 open and building directly it will work correct on my IPhone. 

Any way, it's a very good project, how ever it is implement all functions by native level so it's hard to custom by js in our own project.

Thanks & Best Regards
Sui
